export default function FeedPage() {
    return (
        <>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        <h2>FeedPage</h2>
        </>
    )
}